### ISSUE TITLE
Stuck in LoadingActivity Screen

### ISSUE THREAD

**Issue by fahrishih** [prathmeshranaut/skooterapp#7]
I imported the project in Android Studio and the build was successful. I installed the APK into my phone but for some reason I can't get passed the loading screen. It keeps showing the progress bar and retry button but nothing is working for me. What is wrong here?
![screenshot_20161010-130240](https://cloud.githubusercontent.com/assets/22738442/19227924/fdd1d914-8ee9-11e6-93cd-4d63dac49490.png)

**Comment by prathmeshranaut** [comment]
The API is not up anymore.

**Comment by Sriwliw** [comment]
how can i up a new API or mine

**Comment by prathmeshranaut** [comment]
You'll have to code one at the moment. The API code isn't open source anymore.

**Comment by WasimAkbar** [comment]
Hi @prathmeshranaut nice concept, i need full version of this project for reference, can you please share it, i will be glad if you help me, thanks.

**Comment by prathmeshranaut** [comment]
@Sriwliw @WasimAkbar Uploaded the API built in Ruby for this app https://github.com/prathmeshranaut/skooterapi

**Comment by gauravagrawal-0** [comment]
Can you plz tell me how to use the api with app  ?

**Comment by prathmeshranaut** [comment]
@gauravzuse Setup the API on your server and then update `main_url` in the file `https://github.com/prathmeshranaut/skooterapp/blob/master/app/src/main/res/values/api.xml`

**Comment by gauravagrawal-0** [comment]
Thanku So much

**Comment by byzatwuer** [comment]
hi @prathmeshranaut 

How to edit main url ? What I will write to api.xml after I install the api to the server ?

I will write ip address ?
If not server hostname ?

Skooterapi my server is installed in the root directory Is it in the right place

**Comment by prathmeshranaut** [comment]
If you can load the API via browser then the base URL of that app is the base URL of the API. Use that in the API.xml file

**Comment by byzatwuer** [comment]
I do not understand anything you say sorry @prathmeshranaut
